### ISSUE TITLE
Translation: Needs Spanish translation

### ISSUE THREAD

**Issue by koenvervloesem** [koenvervloesem/snips-app-keep-quiet#5]
https://github.com/koenvervloesem/snips-app-keep-quiet/tree/master/translations

This app needs [entities injection](https://docs.snips.ai/articles/platform/nlu/dynamic-vocabulary) for disabling and enabling intents, which is only supported in English, French and German for now.

**Comment by pepebc** [comment]
OK, I have proposed a new es.py

**Comment by koenvervloesem** [comment]
I don't see a pull request?
